In [1]:
import pandas as pd
import numpy as np

import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.metrics import confusion_matrix , accuracy_score


In [2]:
data = pd.read_csv( 'C:\\Users\\Administrator\\Desktop\\Python\\AI\\Day 3\\iris.csv')
data.head(2)

petallength  petalwidth  sepallength  sepalwidth  species
0          5.1         3.5          1.4         0.2        0
1          4.9         3.0          1.4         0.2        0

In [3]:
x_input  = data.drop( 'species' , axis = 1 )
y_label  = data['species']

In [4]:
y_hot = pd.get_dummies(y_label)
y_hot.head(2)

0  1  2
0  1  0  0
1  1  0  0

In [5]:
y_hot = y_hot.values

In [6]:
y_hot[ :2 , ]

array([[1, 0, 0],
       [1, 0, 0]], dtype=uint8)

In [7]:
x = tf.placeholder( tf.float32 , [None , 4] )
y = tf.placeholder( tf.float32 , [None , 3] )



In [24]:
tf.truncated_normal?

In [8]:
#weight and bias - Layer 1

weight1 = tf.Variable( tf.truncated_normal([4,300] ,stddev = 0.1) )
bias1 = tf.Variable( tf.truncated_normal([300] , stddev = 0.1) )

netinput1 = tf.add( tf.matmul(x , weight1) , bias1 )
output1 =tf.nn.relu(netinput1)

In [9]:
#weight and bias - Layer 2

weight2 = tf.Variable( tf.truncated_normal([300,200] ,stddev = 0.1) )
bias2 = tf.Variable( tf.truncated_normal([200] , stddev = 0.1) )

netinput2 = tf.add( tf.matmul(output1 , weight2) , bias2 )
output2 =tf.nn.relu(netinput2)

In [10]:
#weight and bias - Layer 3

weight3 = tf.Variable( tf.truncated_normal([200,50] ,stddev = 0.1) )
bias3 = tf.Variable( tf.truncated_normal([50] , stddev = 0.1) )

netinput3 = tf.add( tf.matmul(output2 , weight3) , bias3 )
output3 =tf.nn.relu(netinput3)

In [12]:
#weight and bias - Layer 4

weight4 = tf.Variable( tf.truncated_normal([50,3] ,stddev = 0.1) )
bias4 = tf.Variable( tf.truncated_normal([3] , stddev = 0.1) )

netinput4 = tf.add( tf.matmul(output3 , weight4) , bias4 )
output4 =tf.nn.softmax(netinput4)

In [13]:


# define the cost loss function for optimizer
loss = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits_v2(labels = y , logits = output4 ) )

#optimizer
gdo = tf.train.GradientDescentOptimizer(learning_rate = 0.01)

train = gdo.minimize( loss )

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

In [ ]:
sess.run(bias)

In [23]:
train

<tf.Operation 'GradientDescent' type=NoOp>

In [14]:
for i in range( 10000 ):
    final_train = sess.run( train , feed_dict = { x : x_input , y : y_hot } )

In [22]:
x_input

petallength  petalwidth  sepallength  sepalwidth
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0         3.6          1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows x 4 columns]

In [20]:
y_hot

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [16]:
predict = sess.run( output4 , feed_dict = { x : x_input } )
predict[ :2 , ]

array([[9.9983525e-01, 1.6476715e-04, 2.0934948e-28],
       [9.9958175e-01, 4.1825441e-04, 4.4578838e-26]], dtype=float32)

In [17]:
result = sess.run( tf.argmax( predict , 1 ) )
result

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [18]:
confusion_matrix( y_label , result )

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  0, 50]], dtype=int64)

In [19]:
accuracy_score( y_label , result )

0.98