In [2]:
pip install joblib

  Using cached https://files.pythonhosted.org/packages/28/5c/cf6a2b65a321c4a209efcdf64c2689efae2cb62661f8f6f4bb28547cf1bf/joblib-0.14.1-py2.py3-none-any.whl
Note: you may need to restart the kernel to use updated packages.


In [3]:
import tensorflow as tf

from sklearn.metrics import accuracy_score

In [11]:
x = tf.placeholder( tf.float32 , [None , 2] )
y = tf.placeholder( tf.float32 , [None , 1] )

weight = tf.Variable( tf.zeros([2,1]) )
bias = tf.Variable( tf.zeros([1]) )

init_op = tf.global_variables_initializer()

I = tf.add( tf.matmul(x,weight) , bias )

output = tf.sigmoid(I)

individual_loss = tf.nn.sigmoid_cross_entropy_with_logits( labels = y , logits = output )

loss = tf.reduce_mean( individual_loss) 

gdo = tf.train.GradientDescentOptimizer( learning_rate = 0.01 )

train = gdo.minimize( loss )

In [12]:
sess = tf.Session()
sess.run(init_op)

In [13]:
print( 'weight : \n' , sess.run( weight ) )
print( 'bias : \n' , sess.run( bias ) )

weight : 
 [[0.]
 [0.]]
bias : 
 [0.]


In [14]:
x_input = [ [0,0] , [0,1] , [1,0] , [1,1] ]
y_input = [[0],[1],[1],[1]]

In [15]:
sess.run( train , feed_dict = { x : x_input , y : y_input } )

In [16]:
print( 'weight : \n' , sess.run( weight ) )
print( 'bias : \n' , sess.run( bias ) )

weight : 
 [[0.00047193]
 [0.00047193]]
bias : 
 [0.00031885]


In [17]:
result = sess.run( output , feed_dict = { x : x_input , y : y_input } )

result.round()


array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

# Not accurate so iterate throught the loop

In [18]:
for i in range(10000) :
    sess.run( train , feed_dict = { x : x_input , y : y_input } )

In [20]:
result = sess.run( output , feed_dict = { x : x_input , y : y_input } )

y_pred = result.round()

y_pred

array([[0.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [31]:
result

array([[0.38464698],
       [0.8231559 ],
       [0.8231559 ],
       [0.9719585 ]], dtype=float32)

In [32]:
accuracy_score( y_input , y_pred )

1.0

In [35]:
print( 'weight : \n' , sess.run( weight ) )
print( 'bias : \n' , sess.run( bias ) )

weight : 
 [[2.0077474]
 [2.0077474]]
bias : 
 [-0.46987024]


# Inference 

In [28]:
x1 = [ [0,0] ]

pred_result = sess.run( output , feed_dict = {x : x1 } )

print(pred_result)

print(pred_result.round())

[[0.38464692]]
[[0.]]
