In [1]:
import tensorflow as tf

import pandas as pd
import numpy as np

from sklearn.metrics import accuracy_score , confusion_matrix

In [2]:
# 200 , 100 , 60 , 30 , 10 

In [3]:
from tensorflow.examples.tutorials.mnist import input_data 

In [4]:
mnist = input_data.read_data_sets('MNIST_data/' , one_hot = True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [ ]:
mnist.train.images.shape

In [ ]:
mnist.train.images

In [ ]:
mnist.train.num_examples

In [ ]:
mnist.test.images.shape

In [ ]:
mnist.test.images

In [ ]:
mnist.validation.images.shape

In [ ]:
mnist.validation.images

In [ ]:
mnist.train.images[200].shape

In [ ]:
mnist.train.images[200].min()

In [ ]:
mnist.train.images[200].max()

In [ ]:
#  mnist.train.images[200]

# Visualizing the data

In [5]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# mnist.train.images[200].reshape(28,28)

In [ ]:
plt.imshow( mnist.train.images[200].reshape(28,28) )

In [ ]:
plt.imshow(mnist.train.images[7400].reshape(14,56))

In [ ]:
batch_x , batch_y = mnist.train.next_batch(200)  # random 200 values

In [ ]:
mnist.train.images[200][ : 3]

In [ ]:
mnist.train.labels[200]

In [ ]:
batch_x.shape

In [ ]:
batch_y.shape

In [ ]:
plt.imshow( batch_x[148].reshape(28,28) )

In [ ]:
batch_y[148].argmax()   # label of the number

# Create the Model with multi later neuron ( 200 , 100 , 60 , 30 ) 10 - class

In [15]:
# place holder to read value and label at runtime
x = tf.placeholder( tf.float32 , shape = [None , 784] )
y_true = tf.placeholder( tf.float32 , shape = [None , 10] )



In [16]:
# weight and bias for layer 1

weight1 = tf.Variable( tf.truncated_normal([784 , 200]  , stddev = 0.1) )
bias1 = tf.Variable( tf.truncated_normal([200] , stddev = 0.1) )

netinput1 = tf.add( tf.matmul(x,weight1) , bias1 )

output1 = tf.nn.relu(netinput1)

In [17]:
# weight and bias for layer 2

weight2 = tf.Variable( tf.truncated_normal([200 , 100] , stddev = 0.1) )
bias2 = tf.Variable( tf.truncated_normal([100] , stddev = 0.1) )

netinput2 = tf.add( tf.matmul(output1,weight2) , bias2 )

output2 = tf.nn.relu(netinput2)

In [18]:
# weight and bias for layer 3

weight3 = tf.Variable( tf.truncated_normal([100 , 60] , stddev = 0.1) )
bias3 = tf.Variable( tf.truncated_normal([60] , stddev = 0.1) )

netinput3 = tf.add( tf.matmul(output2,weight3) , bias3 )

output3 = tf.nn.relu(netinput3)

In [19]:
# weight and bias for layer 4

weight4 = tf.Variable( tf.truncated_normal([60 , 30] , stddev = 0.1) )
bias4 = tf.Variable( tf.truncated_normal([30] , stddev = 0.1 ) )

netinput4 = tf.add( tf.matmul(output3,weight4) , bias4 )

output4 = tf.nn.relu(netinput4)

In [20]:
# weight and bias for layer 5 

weight5 = tf.Variable( tf.truncated_normal([30 , 10] , stddev = 0.1) )
bias5 = tf.Variable( tf.truncated_normal([10] , stddev = 0.1) )

netinput5 = tf.add( tf.matmul(output4,weight5) , bias5 )

output5 = tf.nn.softmax(netinput5)

In [21]:
# Loss Function 

loss_function = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits_v2( labels = y_true , logits = output5 ) )

# Optimizer 

gdo = tf.train.GradientDescentOptimizer( learning_rate = 0.5 )

train = gdo.minimize(loss_function)

In [22]:
# create session
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [23]:
for step in range(40000):
    batch_x , batch_y = mnist.train.next_batch(200)
    sess.run( train , feed_dict = { x : batch_x , y_true : batch_y } )

In [24]:
predict = sess.run( output5 , feed_dict = { x : mnist.test.images } )
predict

array([[5.8597250e-34, 5.5288870e-25, 5.2025673e-20, ..., 1.0000000e+00,
        6.8519219e-32, 2.4103167e-20],
       [3.7949775e-24, 1.2291132e-19, 1.0000000e+00, ..., 2.9168879e-25,
        3.8470224e-19, 2.1438236e-33],
       [6.3244679e-21, 9.9999988e-01, 3.2564693e-10, ..., 1.2237859e-07,
        1.5394924e-09, 1.0416441e-18],
       ...,
       [3.1103169e-36, 3.4579829e-21, 1.9070323e-26, ..., 9.9109439e-24,
        2.7115676e-25, 3.5911646e-23],
       [4.4207253e-18, 2.1048746e-21, 4.9791310e-22, ..., 1.5846541e-21,
        2.5418337e-12, 5.9465549e-19],
       [5.1106373e-24, 2.2363104e-33, 2.0237840e-20, ..., 0.0000000e+00,
        5.3687989e-28, 0.0000000e+00]], dtype=float32)

In [25]:
print( mnist.test.images.shape )
print( predict.shape )

(10000, 784)
(10000, 10)


In [26]:
result = sess.run( tf.argmax( predict , axis = 1 ) )
result

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [27]:
result.shape

(10000,)

In [28]:
labhot = sess.run( tf.argmax(mnist.test.labels , axis = 1 ) )
labhot

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [29]:
accuracy_score( labhot , result )

0.978

# Validation set

In [ ]:
# test with a single image
# fetch one image

test_image , test_label = mnist.validation.next_batch( 1 )

In [ ]:
# run inference 

mymax = tf.argmax( softmaxoutput , 1 )
print("Predicted Value : ")
print( sess.run(mymax , feed_dict = { x : test_image} ) )

In [ ]:
plt.imshow( test_image.reshape(28,28) )