In [3]:
import pandas as pd
import numpy as np

import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.metrics import confusion_matrix , accuracy_score


In [4]:
data = pd.read_csv( 'iris.csv')
data.head(2)

petallength  petalwidth  sepallength  sepalwidth  species
0          5.1         3.5          1.4         0.2        0
1          4.9         3.0          1.4         0.2        0

In [5]:
x_input  = data.drop( 'species' , axis = 1 )
y_label  = data['species']

In [7]:
y_hot = pd.get_dummies(y_label)
y_hot.head(2)

0  1  2
0  1  0  0
1  1  0  0

In [8]:
y_hot = y_hot.values

In [10]:
y_hot[ :2 , ]

array([[1, 0, 0],
       [1, 0, 0]], dtype=uint8)

In [14]:
x = tf.placeholder( tf.float32 , [None , 4] )
y = tf.placeholder( tf.float32 , [None , 3] )

#weight and bias
weight = tf.Variable( tf.truncated_normal([4,3] ,stddev = 0.1) )
bias = tf.Variable( tf.truncated_normal([3] , stddev = 0.1) )

netinput = tf.add( tf.matmul(x , weight) , bias )
output =tf.nn.softmax(netinput)

# define the cost loss function for optimizer
loss = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits_v2(labels = y , logits = output ) )

#optimizer
gdo = tf.train.GradientDescentOptimizer(learning_rate = 0.01)

train = gdo.minimize( loss )

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)

In [21]:
sess.run(bias)

array([ 0.12414765,  0.01610037, -0.04167465], dtype=float32)

In [23]:
for i in range( 10000 ):
    final_train = sess.run( train , feed_dict = { x : x_input , y : y_hot } )

In [25]:
predict = sess.run( output , feed_dict = { x : x_input } )
predict[ :2 , ]

array([[9.8386139e-01, 1.6138364e-02, 2.9172520e-07],
       [9.5653206e-01, 4.3465927e-02, 2.0221430e-06]], dtype=float32)

In [26]:
result = sess.run( tf.argmax( predict , 1 ) )
result

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [29]:
confusion_matrix( y_label , result )

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  0, 50]], dtype=int64)

In [30]:
accuracy_score( y_label , result )

0.98