In [1]:
import tensorflow as tf

In [8]:
# 1 Find argmax

In [9]:
a1 = tf.Variable( [ [150,250,750] , [500,600,800] , [900,200,450] ,[990,220,330] ])

init_op = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init_op)

In [10]:
sess.run(a1)

array([[150, 250, 750],
       [500, 600, 800],
       [900, 200, 450],
       [990, 220, 330]])

In [11]:
sess.run( tf.argmax( a1 , axis = 0) )

array([3, 1, 1], dtype=int64)

In [12]:
sess.run( tf.argmax( a1 , axis = 1) )

array([2, 2, 0, 0], dtype=int64)

In [14]:
# 2 How many ways this can be reshaped with same rank

In [19]:
l = sess.run(a1).size

In [31]:
c = 0
for i in range(1 , 13 , 1):
    if ( i * (l//i) == 12) :
        c = c + 1
print(c)

6


In [21]:
# 3 Multiplication

In [22]:
sess.run(a1)

array([[150, 250, 750],
       [500, 600, 800],
       [900, 200, 450],
       [990, 220, 330]])

In [27]:
a2 = tf.Variable( [[390],[890],[790]])
init_op = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init_op)
sess.run(a2)

array([[390],
       [890],
       [790]])

In [28]:
sess.run( tf.matmul( a1,a2) )

array([[ 873500],
       [1361000],
       [ 884500],
       [ 842600]])

In [ ]:
# sess.run( tf.matmul( a2,a1) )  Error

In [33]:
p1 = tf.Variable([ [1,2,3] , [4,5,6] ] )
p2 = tf.Variable([[7],[8],[9]])

init_op = tf.global_variables_initializer()

sess.run(init_op)

sess.run(tf.matmul(p1,p2))

array([[ 50],
       [122]])

In [38]:
A = tf.Variable( [[1,2,3],[4,5,6],[7,8,9]])
init_op = tf.global_variables_initializer()

sess.run(init_op)

sess.run(tf.argmax(A,0))

array([2, 2, 2], dtype=int64)

In [40]:
A = tf.Variable( [[1,4,3,2],[8,6,7,5],[9,10,11,12]])
init_op = tf.global_variables_initializer()

sess.run(init_op)

sess.run(tf.argmax(A,1))

array([1, 0, 3], dtype=int64)

In [42]:
# 4

In [47]:
# y = x^2 - 20x + 100

x = tf.placeholder( tf.float32 )

y = x**2 - 20*x + 100

for i in range(3):
    ip = float(input("x = "))
    print( sess.run(y , feed_dict={ x : ip}))

x = 5
25.0
x = 10
0.0
x = 20
100.0


In [51]:
# Write a program to solve X^2 - 298*X + 22201 = 0 

x = tf.Variable(100.0)
init_op = tf.global_variables_initializer()
sess.run(init_op)

cost = x**2 - 298 * x + 22201

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(cost)

sess.run(train)

In [52]:
sess.run(x)

100.98

In [55]:
for i in range(1000):
    sess.run(train)
sess.run(x)

148.99963

In [56]:
# 5

In [58]:
x = tf.Variable(100.0)
y = tf.constant(20.0)
z = tf.placeholder(tf.float32)

a = x + y 
b = z * a

init_op = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init_op)

sess.run(b , feed_dict = {z : 25})

3000.0