In [2]:
import tensorflow as tf

In [2]:
tf.__version__

'1.15.0'

In [ ]:
# Placholder are never stored , they are initialized runtime and their lifescope is till the session is active

### working with scaler

In [20]:
a = tf.placeholder( tf.float32 )
b = tf.placeholder( tf.float32 )

c = a + b 

sess = tf.Session()

print( sess.run( c , feed_dict = {a : 10 , b : 30 }) )

sess.close()

40.0


In [21]:
a = tf.placeholder( tf.float32 )
b = tf.placeholder( tf.float32 )
c = tf.Variable( 30.0 ) # this has to be float else error
init_op = tf.global_variables_initializer()

c = a + b + c

sess = tf.Session()
sess.run(init_op)
print( sess.run( c , feed_dict = {a : 10 , b : 30 }) )

sess.close()

70.0


In [22]:
# Multiple calling of tensorflow

a = tf.placeholder( tf.float32 )
b = tf.placeholder( tf.float32 )

c = a + b 

d = a * c 

sess = tf.Session()

print( sess.run( d , feed_dict = {a : 10 , b : 30 }) )

sess.close()

400.0


In [6]:
# Multiple calling of tensorflow

a = tf.placeholder( tf.float32 )
b = tf.placeholder( tf.float32 )

c = a + b 
sess = tf.Session()
print( sess.run( c , feed_dict = {a : 10 , b : 30 }) )
sess.close()

d = a * c 

sess = tf.Session()

# This will throw error as the placeholder has to be initialized every time , you can not leave thinking we initialized for c

# print( sess.run( d , feed_dict = {a : 10 }) )  # Uncommend and check

sess.close()

40.0


### Working with Arrays

In [23]:
a = tf.placeholder( tf.float32 )
b = tf.placeholder( tf.float32 )

c = a + b 

sess = tf.Session()
print( sess.run( c , feed_dict = {a : [1 , 2 , 3] , b : [4 , 5 , 6] } ) )

sess.close()

[5. 7. 9.]


In [8]:
a = tf.placeholder( tf.float32 )
b = tf.placeholder( tf.float32 )

c = a * b 

sess = tf.Session()

avalues = [1 , 2 , 3]
bvalues = [4 , 5 , 6]

print( sess.run( c , feed_dict = {a : avalues , b : bvalues } ) ) # can be stored in a variable passed as an argument

sess.close()

[ 4. 10. 18.]


In [9]:
a = tf.placeholder( tf.float32 )
b = tf.placeholder( tf.float32 )

c = a + b 

d = c * a

sess = tf.Session()
print( sess.run( d , feed_dict = {a : [1 , 2 , 3] , b : [4 , 5 , 6] } ) )

sess.close()

sess.close()

[ 5. 14. 27.]
