In [1]:
import tensorflow as tf

In [2]:
x = tf.Variable( [1,2,3] )
y = tf.Variable( [4,5,6] )

init_op = tf.global_variables_initializer()

sess = tf.Session()

sess.run(init_op)

In [3]:
sess.run(x + y )

array([5, 7, 9])

In [4]:
sess.run(x * y )

array([ 4, 10, 18])

In [5]:
sess.run(x + 10 )

array([11, 12, 13])

In [6]:
sess.run(x * 10 )

array([10, 20, 30])

# Matrix Multiplication

In [20]:
x = tf.Variable( [ [1,2,3] , [4,5,6] ] )
y = tf.Variable( [[7,8] , [9,10] , [11,12] ] )

init_op = tf.global_variables_initializer()

sess = tf.Session()

sess.run(init_op)

In [21]:
print( sess.run(x) )

[[1 2 3]
 [4 5 6]]


In [22]:
print( sess.run(y) )

[[ 7  8]
 [ 9 10]
 [11 12]]


In [23]:
z = tf.matmul( x , y )


In [24]:
print(sess.run(z))

[[ 58  64]
 [139 154]]


In [25]:
z1 = tf.matmul( y , x )

In [26]:
print(sess.run(z1))

[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


In [27]:
x.shape

TensorShape([Dimension(2), Dimension(3)])

In [28]:
y.shape

TensorShape([Dimension(3), Dimension(2)])

In [18]:
sess.close()