In [1]:
import tensorflow as tf

In [2]:
x = tf.Variable( [2,50,3,10,4,5,6,7] )
y = tf.Variable( [[1,2],[3,4],[5,6]] )
z = tf.Variable( [[1,9],[8,2],[8,7]] )

In [4]:
sess = tf.Session()

init_op = tf.global_variables_initializer()
sess.run(init_op)

In [6]:
print( sess.run(x) )
print( sess.run(y) )
print( sess.run(z) )

[ 2 50  3 10  4  5  6  7]
[[1 2]
 [3 4]
 [5 6]]
[[1 9]
 [8 2]
 [8 7]]


# Reshaping 

In [16]:
sess.run( tf.reshape(x,[4,2]) ) # give the desired shape , such that the no of items has to me same mn

array([[ 2, 50],
       [ 3, 10],
       [ 4,  5],
       [ 6,  7]])

In [22]:
sess.run( tf.reshape(y,[1,6])) 

array([[1, 2, 3, 4, 5, 6]])

In [19]:
sess.run( tf.reshape(z,[1,2,3])) # increasing the rank

array([[[1, 9, 8],
        [2, 8, 7]]])

# Argmax

In [26]:
x = tf.Variable( [2,50,3,10,4,50,6,7] )
y = tf.Variable( [[1,2],[3,4],[5,6]] )
z = tf.Variable( [[1,9],[8,2],[8,7]] )

init_op = tf.global_variables_initializer()
sess.run(init_op)

In [27]:
sess.run( tf.argmax( x , axis = 0) )

1

In [28]:
sess.run( tf.argmax( x ) )

1

In [32]:
sess.run(z)

array([[1, 9],
       [8, 2],
       [8, 7]])

In [29]:
sess.run( tf.argmax( z , axis = 0) )

array([1, 0], dtype=int64)

In [31]:
sess.run( tf.argmax( z , axis = 1) )

array([1, 0, 0], dtype=int64)